In [17]:
import numpy as np
import random

In [18]:
arr1=[]
for i in range(0,3):
    list=[]
    for j in range(0,2):
        list.append(random.randint(0,100))
    arr1.append(list)
array2=np.array(arr1)
print(array2)

[[25 28]
 [66 88]
 [13 63]]


In [19]:
arr2=[]
for i in range(0,2):
    list=[]
    for j in range(0,3):
        list.append(random.randint(0,100))
    arr2.append(list)
array1=np.array(arr2)
print(array1)

[[14 73 96]
 [10 96 40]]


In [20]:
multiplies=np.matmul(array1,array2)

In [23]:
multiplies

array([[ 6416, 12864],
       [ 7106, 11248]])